### PR TITLE
Added second parameter "context" to List.update

### PR DESCRIPTION
**Pull request by katywings**
As discussed in slack ;). The context parameter can be used for many things and its a performance oriented alternative to `Array.map`.

### CODE REVIEW

**Comment by pakastin** [comment]
I hope to have time to merge and release this during the weekend.. 🍼😉

**Comment by katywings** [comment]
No hurry 😃 !

**Comment by pakastin** [comment]
Perfect, thank you! I hadn't noticed documentation was missing `list.update` altogether, so great you added it also! 😎👍

**Comment by pakastin** [comment]
Released with v3.4.0! 🎉
https://github.com/redom/redom/releases/tag/v3.4.0

**Pull request merged**
