### PR TITLE
Made `util` more performant.

### PR DESCRIPTION
**Pull request by def14nt**
Removed more than one `typeof el` check in `util`.

### CODE REVIEW

**Comment by def14nt** [comment]
btw those circ deps are bad

**Comment by def14nt** [comment]
@pakastin

**Comment by pakastin** [comment]
Looks good! 👌
I’ll get to this in about an hour..

**Comment by pakastin** [comment]
Thank you for the contribution, great work! ❤️

**Comment by pakastin** [comment]
Released! https://github.com/redom/redom/releases/tag/v3.13.2

**Comment by jens1o** [comment]
are there any numbers?

**Comment by pakastin** [comment]
It’s clearly doing less and the logic is simpler. Might not be a major performance enhancement, but I like it 👍

**Comment by def14nt** [comment]
Thanks :+1: I'll have a look through the source code for any more things I can make faster :)

**Comment by def14nt** [comment]
On a side note, this library does not get enough attention from what I can see. Have you tried a bit of advertising?

**Pull request merged**
