### PR TITLE
Add support for function and any in Router, Place and ListPool views

### PR DESCRIPTION
**Pull request by czb**

### CODE REVIEW

**Comment by pakastin** [comment]
Thank you! I’ll check this out ASAP 😎👍

**Comment by pakastin** [comment]
This is an issue:
```
function test () {}
class Test { constructor () { } }

isConstructor(Test); // 'Test' == true
isConstructor(test); // 'test' == true
```
🧐

**Comment by pakastin** [comment]
What's the difference between a "class" and a function, really?

Well, this is *not* a class, for sure:
```
const test2 = () => {};

isConstructor(test2); // undefined
```

**Comment by czb** [comment]
I took it from here:

https://stackoverflow.com/questions/40922531/how-to-check-if-a-javascript-function-is-a-constructor

Basically we need to check if the variable has a constructor. It should according to the web look like

```
function isConstructor(obj) {
  return !!obj.prototype && !!obj.prototype.constructor.name;
}
```
I do not know why I removed the exclamation marks...

**Comment by czb** [comment]
I see your point. It is not as easy as it seems:

https://stackoverflow.com/questions/40922531/how-to-check-if-a-javascript-function-is-a-constructor

I really like the idea of not using class if not necessary but for now I have no idea how to implement it. Will have to think a little bit :)

**Comment by pakastin** [comment]
That doesn't matter that much though, since you can call a regular function with `new` and it'll work..

And nowadays fat arrows (and class) are recommended anyway. So maybe that's ok.

**Comment by czb** [comment]
Ok super. 👍

**Comment by pakastin** [comment]
I will add some tests etc ASAP..

**Comment by pakastin** [comment]
Hmm..there's some really weird errors now

**Comment by pakastin** [comment]
I'm not sure if class detection is worth it, but I sure like the idea of having a Node support for `place` etc...

**Comment by pakastin** [comment]
That way you could choose a functional or prototypal ones based on your preference..

**Comment by pakastin** [comment]
..so thank you for these, but will close now and separate the libraries with the next major update

**Pull request closed without merging**
