### PR TITLE
Add middleware

### PR DESCRIPTION
**Pull request by def0x099**
This pull request adds primitive middleware support to redom, which should render passing functions to redom functions obsolete. :tada:

### CODE REVIEW

**Comment by def14nt** [comment]
Can someone help with this? I'm lost.
Here's a log of `npm run build && npm run minify && npm run test` on my machine:
```
# /home/def14nt/Desktop/code/Forks/redom/test/redom.js: line 342, column 54-59

      for (var i = 0, list = mwFuncs; i < list.length; i += 1) {
                                                       ^^^^^^

# /home/def14nt/Desktop/code/Forks/redom/test/redom.js: line 343, column 7-25

        var func = list[i];
        ^^^^^^^^^^^^^^^^^^^

# /home/def14nt/Desktop/code/Forks/redom/test/redom.js: line 345, column 7-53

        func.apply(void 0, [ element ].concat( args )); // execute middleware
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

# /home/def14nt/Desktop/code/Forks/redom/test/redom.js: line 586, column 3-41

    var funcs = [], len = arguments.length;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

# /home/def14nt/Desktop/code/Forks/redom/test/redom.js: line 587, column 11-15, 11-15

    while ( len-- ) funcs[ len ] = arguments[ len ];
            ^^^^^   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

# /home/def14nt/Desktop/code/Forks/redom/test/redom.js: line 589, column 16-16, 16-16, 16-16, 16-16

    for (var i = 0, list = funcs; i < list.length; i += 1) {
                 ^         ^^^^^  ^^^^^^^^^^^^^^^  ^^^^^^

# /home/def14nt/Desktop/code/Forks/redom/test/redom.js: line 590, column 5-23

      var func = list[i];
      ^^^^^^^^^^^^^^^^^^^

# /home/def14nt/Desktop/code/Forks/redom/test/redom.js: line 592, column 9-34

      if (typeof func !== 'function') {
          ^^^^^^^^^^^^^^^^^^^^^^^^^^

# /home/def14nt/Desktop/code/Forks/redom/test/redom.js: line 593, column 13-48

        throw new TypeError('expected a function');
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

# /home/def14nt/Desktop/code/Forks/redom/test/redom.js: line 597, column 3-37

    mwFuncs.push.apply(mwFuncs, funcs);
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by def14nt** [comment]
@pakastin Can you add tests for this? Not sure about the syntax, and I'm hitting a brick wall still.

**Comment by pakastin** [comment]
I can add tests, yeah. It’s now middle of the night though and tomorrow is fathers day, so I’ll try to have time, otherwise on monday.

**Comment by def14nt** [comment]
lol that edit history for that comment tho :laughing: ok good luck, ping me if you need anything

**Comment by pakastin** [comment]
Will check out tomorrow, just came home from this big playground with children and I’m so done for today 😴

**Comment by def14nt** [comment]
lol ok, take a nap :smile:

**Comment by pakastin** [comment]
Oh gosh, sorry I've totally forgot about this, and now going to bed – I'll try to have some time tomorrow..

**Comment by def14nt** [comment]
Closing due to inactivity.

**Comment by def14nt** [comment]
@pakastin

**Comment by pakastin** [comment]
Ok, I'm not exactly sure what's the point with global middleware?

**Comment by def14nt** [comment]
@pakastin Seeing as it's been 4 months, I've been anticipating a more fruitful response than that. If you actually *looked* at what this fixes, you'd understand why it's a much better alternative. I think I've been relatively nice, and I've had empty promises from you that have lasted a long time. If you can't be bothered, feel free to close this pull request, as I'm done at this point.

**Comment by pakastin** [comment]
I do understand the idea of a middleware, but why for every single element? I’m just concerned about how it will affect the performance.

**Comment by def14nt** [comment]
Performance shouldn't be a problem, unless you go crazy with it. I think anything over or equal to 40/50 middleware functions would affect performance negativity.

**Comment by def14nt** [comment]
Having a middleware handler makes composing components in RE:DOM easier, as it saves you the bother of having to input the function every time. Do you think this will have a negative impact on readability if people abuse this, though?

I can see confusion arising when people try to debug middleware, because for one the order is implicit. Middleware *can* modify elements, but there may be bugs when you defer the loading of your middleware, e.g `import()`. 

In light of these disadvantages, middleware is somewhat dangerous to the user. It should only be used by global functions e.g `redom-plugin-x`. 

Do you think users resorting to an array of plugins, and then just piping the element through them by using `...plugins` is preferable? 

The point of redom is to be simple, but maybe this is a step backwards. Open for feedback.

**Comment by pakastin** [comment]
I will think about this 👍

**Comment by pakastin** [comment]
Sorry to inform, but I don't want to have middlewares for every elements. You can already compose components by creating a component class (or factory).

**Comment by def0x099** [comment]
@pakastin Should we try a poll? This seems like a useful feature

**Comment by def0x099** [comment]
@pakastin I would encourage you to provide a little more information when closing pull requests, and to let the community decide on features (e.g a poll).

**Comment by talmobi** [comment]
@def0x099 I like this PR. It's clean and organised. However, I don't think it adds anything new that couldn't have been achieved before. I agree with your own criticisms of the PR in your earlier comment: https://github.com/redom/redom/pull/125#issuecomment-464526246

I think it's somewhat of an anti-pattern considering what and how you can already achieve these things in redom.

Polling the community makes sense for larger more involved projects that have multiple active core-maintainers, I don't think it would result into insightful outcomes in this case where there's only one of those.

Middleware support as such isn't a bad idea, but in this case I think it adds an unnecessary layer of complexity and choice. And in accordance with King Henrik: https://twitter.com/HenrikJoreteg/status/364989455414726657

Unless perhaps you have some practical examples of what this PR would solve significantly better as opposed standard component compositions?

2cents~

**Comment by pakastin** [comment]
I agree with @talmobi!

**Comment by katywings** [comment]
Middleware Layers always add complexity and abstraction. The way I see it is that the existing implemention isnt really the same "middleware" as you often see it in systems like express or redux. The difference between redom middleware and middleware as one often sees it in other systems is, normally middleware is defined "per system, all systemchildren" (Application instance level), not per "some child of system" (Function call level) - imho the current implementation is more like an "afterCreate" handler. And thats not to say that i dont like the current implemention - just saying it for clarification.

Redom doesnt have a concept of "global instance" as far as i know, which obviously makes it easier to understand and maintain.

A good middleware implementation requires, that you as example can render multiple application instances in parallel with different middleware (as example when test runners run in parallel), which is not possible with the middleware proposed in this pr as far as i know.

The existing redom middleware in the other hand could be used as a kinda middleware layer only if the lib user manually always adds his middleware abstraction to all el function calls xD or if he creates an own "per application instance"-el function wrapper which also is an awful dev experience - but possible :D. The important part of middleware is, that its abstraction applies to "all of something", not just some of it :).

**Comment by katywings** [comment]
Oh and just to repeat: I dont say that i am for or against middleware. 
The only importabt question is: Does redom  embrace simplicity or customizability? ;)

**Comment by mrwanashraf** [comment]
@katywings  That's a great question, I do think that simplicity leads to customization, but of course as far as i know, redom embraces simplicity. 
isn't it @pakastin?

**Comment by def0x099** [comment]
@katywings Great response. Thanks for taking the time to type that up, as it really does highlight how redom doesn't *really* have a middleware implementation (yet).

An idea came to mind

**Pull request closed without merging**
